//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectPP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _360_F_276959928_MzW1FMER5GDM51fsFgmzjcWHzTeP5UYI {
            get {
                object obj = ResourceManager.GetObject("360_F_276959928_MzW1FMER5GDM51fsFgmzjcWHzTeP5UYI", resourceCulture);
=======
        internal static System.Drawing.Bitmap licensed_image {
            get {
                object obj = ResourceManager.GetObject("licensed-image", resourceCulture);
>>>>>>> 8bbd8768ba6ebebbf8082d60147ab9018198fd60
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap _360_F_303116781_NH1kEe07K7XLNYksNMF3jqP8QLsh6ucJ {
            get {
                object obj = ResourceManager.GetObject("360_F_303116781_NH1kEe07K7XLNYksNMF3jqP8QLsh6ucJ", resourceCulture);
=======
        internal static System.Drawing.Bitmap New_blog_graphic_16 {
            get {
                object obj = ResourceManager.GetObject("New-blog-graphic-16", resourceCulture);
>>>>>>> 8bbd8768ba6ebebbf8082d60147ab9018198fd60
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap c8f7bdd3e52c315dafb9641f92672498 {
            get {
                object obj = ResourceManager.GetObject("c8f7bdd3e52c315dafb9641f92672498", resourceCulture);
=======
        internal static System.Drawing.Bitmap New_blog_graphic_161 {
            get {
                object obj = ResourceManager.GetObject("New-blog-graphic-161", resourceCulture);
>>>>>>> 8bbd8768ba6ebebbf8082d60147ab9018198fd60
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap gradient_prism_database_mn7r5oitvwwid6yg {
            get {
                object obj = ResourceManager.GetObject("gradient-prism-database-mn7r5oitvwwid6yg", resourceCulture);
=======
        internal static System.Drawing.Bitmap New_blog_graphic_162 {
            get {
                object obj = ResourceManager.GetObject("New-blog-graphic-162", resourceCulture);
>>>>>>> 8bbd8768ba6ebebbf8082d60147ab9018198fd60
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
<<<<<<< HEAD
        internal static System.Drawing.Bitmap HD_wallpaper_dark_blue_windows_10_logo_background_windows_10 {
            get {
                object obj = ResourceManager.GetObject("HD-wallpaper-dark-blue-windows-10-logo-background-windows-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2_ {
            get {
                object obj = ResourceManager.GetObject("images (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1220651314_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1220651314-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1680577207_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1680577207-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lovepik_modern_technology_wallpaper_background_image_500482213 {
            get {
                object obj = ResourceManager.GetObject("lovepik-modern-technology-wallpaper-background-image_500482213", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OMS_for_Media_Companies_v1 {
            get {
                object obj = ResourceManager.GetObject("OMS-for-Media-Companies-v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_blue_artificial_intelligence_future_technology_background_picture_image_1143086 {
            get {
                object obj = ResourceManager.GetObject("pngtree-blue-artificial-intelligence-future-technology-background-picture-image_1" +
                        "143086", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_blue_glowing_line_circuit_background_image_718715 {
            get {
                object obj = ResourceManager.GetObject("pngtree-blue-glowing-line-circuit-background-image_718715", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_fashion_blue_ai_future_technology_background_image_950143 {
            get {
                object obj = ResourceManager.GetObject("pngtree-fashion-blue-ai-future-technology-background-image_950143", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_technology_background_template_image_339979 {
            get {
                object obj = ResourceManager.GetObject("pngtree-technology-background-template-image_339979", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap strip_texture_dark_blue_wallpaper_preview {
            get {
                object obj = ResourceManager.GetObject("strip-texture-dark-blue-wallpaper-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2025_06_18_at_22_57_21_e144fbd9 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2025-06-18 at 22.57.21_e144fbd9", resourceCulture);
=======
        internal static System.Drawing.Bitmap pngtree_reset_password_to_gain_more_secure_account_png_image_8920326 {
            get {
                object obj = ResourceManager.GetObject("pngtree-reset-password-to-gain-more-secure-account-png-image_8920326", resourceCulture);
>>>>>>> 8bbd8768ba6ebebbf8082d60147ab9018198fd60
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
